# SonarCloud — SmartTax Frontend (Angular)
#
# En CI (GitHub Actions) : organisation et token viennent des secrets
#   SONAR_ORGANIZATION  +  SONAR_TOKEN
#
# Organization Key : https://sonarcloud.io > yassinedhahbi > Organization Key

sonar.projectKey=yassinedhahbi_smarttax-frontend
sonar.projectName=SmartTax Frontend
sonar.organization=yassinedhahbi

sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/src/assets/**,**/global-shim.ts
sonar.test.inclusions=**/*.spec.ts

sonar.coverage.exclusions=**/*
sonar.qualitygate.wait=true
