spring.application.name=ArabSoftBack
spring.datasource.url=jdbc:postgresql://192.168.144.141:5432/ArabSoft_db
spring.datasource.username=postgres
spring.datasource.password=MonPass123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/

# Configuration Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yassinedhahbi65@gmail.com
spring.mail.password=wppn ftaw razm icov
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

ai.model.path=classpath:models/swin_cin_classifier.pt
ai.model.input-size=224


training.data.path=C:/Users/yassi/Desktop/Stage ArabSoft/swin_transformer_project
# Configuration du logging
logging.level.tn.esprit.arabsoftback=DEBUG
logging.file.name=arabsoft.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
# recaptcha


recaptcha.secret.key=6LeTs3grAAAAANs8SLXS6lxDN8y3nTl1i0yekH1a


